settings:
  purge_ok: False
  mirror_ok: True

gphotos:
#  host: 'mongodb://labroid:mlab14@ds057176.mlab.com:57176/photo-meta'
#  database: 'photo-meta'
#  collection: 'gphotos'
  host: 'localhost'
  database: 'gp'
  collection: 'gphotos'
  gphoto_db_alias: 'gphotos'

local:
  gphoto_upload_queue: "C:\\Users\\SJackson\\Pictures\\GooglePhotosQueue"
  mirror_root: "C:\\Users\\SJackson\\Pictures\\gphoto_mirror"
  image_filetypes: ['.jpg', '.jpeg', '.bmp', '.mov', '.gif', '.tif', '.tiff', '.fpx']
  log_file_base: "C:\\Users\\SJackson\\Documents\\Personal\\Programming"
  mongod_path: "C:\\Program Files\\MongoDB\\Server\\3.2\\bin\\mongod.exe"
  database: "photo_manager"

path_history:
  host: 'localhost'
  database: 'path_history'
  collection: 'path_history'